name: build-test

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    # input for the dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: sudo apt update && sudo apt install -y cmake g++
      - name: clone external public repos
        run: | 
          cd ..
          git clone https://github.com/VincentFabricio/RobotCmd.git
          ls
      - name: clone external private repos
        run: git clone https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/VincentFabricio/readme.git
      - name: list directories
        run: ls
      - name: compilation
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
      - name: upload generated exec
        uses: actions/upload-artifact@v4
        with:
          name: robot cmq seq executable
          path: build/robot_cmq_seq
          retention-days: 7
